// src/components/CodeEditor.tsx
import { useRef, useEffect } from "react";
import { EditorState } from "@codemirror/state";
import { EditorView, lineNumbers, highlightActiveLine, highlightActiveLineGutter, keymap } from "@codemirror/view";
import { history, historyKeymap, defaultKeymap, indentWithTab } from "@codemirror/commands";
import { bracketMatching, foldGutter, indentOnInput } from "@codemirror/language";
import { closeBrackets, closeBracketsKeymap } from "@codemirror/autocomplete";
import { javascript } from "@codemirror/lang-javascript";
import { editorTheme, syntaxColors } from "./codeMirrorTheme";

interface CodeEditorProps {
  code: string;
  onChange: (code: string) => void;
}

export function CodeEditor({ code, onChange }: CodeEditorProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const viewRef = useRef<EditorView | null>(null);
  const lastCodeRef = useRef(code);
  const onChangeRef = useRef(onChange);

  onChangeRef.current = onChange;

  useEffect(() => {
    if (!containerRef.current) return;

    const state = EditorState.create({
      doc: code,
      extensions: [
        lineNumbers(),
        highlightActiveLine(),
        highlightActiveLineGutter(),
        history(),
        bracketMatching(),
        closeBrackets(),
        foldGutter(),
        indentOnInput(),
        javascript({ typescript: true }),
        editorTheme,
        syntaxColors,
        keymap.of([
          ...closeBracketsKeymap,
          ...defaultKeymap,
          ...historyKeymap,
          indentWithTab,
        ]),
        EditorView.updateListener.of((update) => {
          if (update.docChanged) {
            const newCode = update.state.doc.toString();
            lastCodeRef.current = newCode;
            onChangeRef.current(newCode);
          }
        }),
      ],
    });

    const view = new EditorView({
      state,
      parent: containerRef.current,
    });

    viewRef.current = view;
    lastCodeRef.current = code;

    return () => {
      view.destroy();
      viewRef.current = null;
    };
    // Only run on mount/unmount
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const view = viewRef.current;
    if (!view) return;

    if (code !== lastCodeRef.current) {
      lastCodeRef.current = code;
      view.dispatch({
        changes: { from: 0, to: view.state.doc.length, insert: code },
      });
    }
  }, [code]);

  return (
    <div className="code-panel">
      <div ref={containerRef} style={{ flex: 1, overflow: "hidden" }} />
    </div>
  );
}

// src/components/CodeEditor.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { EditorView, basicSetup } from 'codemirror';
	import { javascript } from '@codemirror/lang-javascript';
	import { EditorState } from '@codemirror/state';
	import { oneDark } from '@codemirror/theme-one-dark';

	let { code = '', onCodeChange }: { code: string; onCodeChange: (newCode: string) => void; } = $props();

	let container: HTMLDivElement;
	let view: EditorView | null = null;

	onMount(() => {
		const state = EditorState.create({
			doc: code,
			extensions: [
				basicSetup,
				javascript({ typescript: true }),
				oneDark,
				EditorView.updateListener.of((update) => {
					if (update.docChanged) onCodeChange(update.state.doc.toString());
				}),
			],
		});
		view = new EditorView({ state, parent: container });
	});

	onDestroy(() => { view?.destroy(); });

	$effect(() => {
		if (view && code !== view.state.doc.toString()) {
			view.dispatch({ changes: { from: 0, to: view.state.doc.length, insert: code } });
		}
	});
</script>

<div bind:this={container} style="height:100%;overflow:auto;"></div>
